apiVersion: v1
kind: Service
metadata:
  name: result-lb
  annotations:
   service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "false"
spec:
  type: LoadBalancer
  selector:
    app: result
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

