name: Build and Scan
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build the Worker Docker image
      run: docker build ${{ github.workspace }}/example-voting-app/worker --file Dockerfile --tag sysdiglabs/worker-vuln-app:latest

    - name: Build the Vote Docker image
      run: docker build ${{ github.workspace }}/example-voting-app/vote --file Dockerfile --tag sysdiglabs/vote-vuln-app:latest

    - name: Build the Result Docker image
      run: docker build ${{ github.workspace }}/example-voting-app/result --file Dockerfile --tag sysdiglabs/result-vuln-app:latest

    - name: Scan image
      id: scan_worker
      uses: sysdiglabs/scan-action@v3
      with:
        image-tag: "sysdiglabs/worker-vuln-app:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        input-type: docker-daemon
        run-as-user: root

    - name: Scan image
      id: scan_vote
      uses: sysdiglabs/scan-action@v3
      with:
        image-tag: "sysdiglabs/vote-vuln-app:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        input-type: docker-daemon
        run-as-user: root

    - name: Scan image
      id: scan_result
      uses: sysdiglabs/scan-action@v3
      with:
        image-tag: "sysdiglabs/result-vuln-app:latest"
        sysdig-secure-token: ${{ secrets.SYSDIG_SECURE_TOKEN }}
        input-type: docker-daemon
        run-as-user: root
